app/__init__.py
from flask import Flask

import mysql.connector

# Conectarse con la base de datos
db = mysql.connector.connect( # LLAMAMOS AL FUNCION CONNECT PARA CONECTARNOS
    host ='informatica.iesquevedo.es',
    port = 3333,
    user ='root', #USUARIO QUE USAMOS NOSOTROS
    password ='1asir', #CONTRASEÑA CON LA QUE NOS CONECTAMOS
    database='kilian'
)


# Importar las rutas
def create_app():
    app = Flask(__name__)
    app.debug = True
    

    

    from .routes import routes_croacia
    from .routes import routes_espana
    from .routes import routes_irlanda
    from .routes import routes_ciudades
    from .routes import routes_paises
    from .routes import routes_personajes
    app.register_blueprint(routes_croacia.rutas_croacia)
    app.register_blueprint(routes_espana.rutas_espana)
    app.register_blueprint(routes_irlanda.rutas_irlanda)
    app.register_blueprint(routes_ciudades.rutas_ciudades)
    app.register_blueprint(routes_paises.rutas_paises)
    app.register_blueprint(routes_personajes.rutas_personajes)
    

    return app

app/routes/routes_ciudades.py
from flask import Flask, Blueprint, render_template, request, redirect, url_for

from app import db
from app.data.ciudad_dao import Ciudades_dao
from app.data.pais_dao import Pais_dao

rutas_ciudades = Blueprint("ruta_ciudad", __name__)

@rutas_ciudades.route('/')
def index():
    return render_template('adminciudades.html')

@rutas_ciudades.route('/verciudad', methods=['POST','GET'])
def verciudad():
    Ciudades = list()
    nombrePais = ""
    pais_dao = Pais_dao()
    paises = pais_dao.select_all(db)

    if (request.method == 'POST'):
        id_paises = request.form['id_paises']
        ciudad_dao = Ciudades_dao()
        Ciudades = ciudad_dao.select_all(db,id_paises)
        for pais in paises:
            
            if (id_paises == int(pais.id)):
               
                nombrePais = pais.nombre



    return render_template('adminciudades.html',ciudades=Ciudades,
                           paises=paises,
                           nombrePais=nombrePais)

@rutas_ciudades.route('/addciudad', methods=['POST'])   
def addciudad():
    ciudad_dao = Ciudades_dao()
    ciudades = request.form['ciudades']
    contenido = request.form['contenido']
    id_paises = request.form['id_paises']

    if (ciudades == "" or contenido == "" or id_paises == ""):
        return redirect(url_for('ruta_ciudad.verciudad'))

    ciudad_dao.insert(db,ciudades,contenido,id_paises)
  
    return redirect(url_for('ruta_ciudad.verciudad')) 

@rutas_ciudades.route('/delciudad', methods=['POST'])   
def delciudad():
    id = request.form['id']
    ciudad_dao = Ciudades_dao()
    ciudad_dao.delete(db,id)
    
   
    return redirect(url_for('ruta_ciudad.verciudad'))  

@rutas_ciudades.route('/updateciudad', methods=['POST'])   
def updateciudad():
    ciudad_dao = Ciudades_dao()

    id = request.form['id']
    ciudades = request.form['ciudades']
    contenido = request.form['contenido']

    if (ciudades == ""):
        return redirect(url_for('ruta_ciudad.verciudad'))

    
    ciudad_dao.update(db,id,ciudades,contenido)
   
    return redirect(url_for('ruta_ciudad.verciudad'))

app/routes/routes_croacia.py
from flask import Flask, Blueprint, render_template, request, redirect, url_for



rutas_croacia = Blueprint("ruta_croacia", __name__)

@rutas_croacia.route('/')
def index():
    return render_template('index.html')

@rutas_croacia.route('/vercroacia')
def vercroacia():
    return render_template('croacia/croacia.html')

@rutas_croacia.route('/zagreb')
def verzagreb():
    return render_template('croacia/zagreb.html')

@rutas_croacia.route('/zadar')
def verzadar():
    return render_template('croacia/zadar.html')

@rutas_croacia.route('/split')
def versplit():
    return render_template('croacia/split.html')

app/routes/routes_espana.py
from flask import Flask, Blueprint, render_template, request, redirect, url_for

rutas_espana = Blueprint("ruta_espana", __name__)

@rutas_espana.route('/')
def index():
    return render_template('index.html')

@rutas_espana.route('/verespana')
def verespana():
    return render_template('españa/espana.html')

@rutas_espana.route('/madrid')
def vermadrid():
    return render_template('españa/madrid.html')

@rutas_espana.route('/barcelona')
def verbarcelona():
    return render_template('españa/barcelona.html')

@rutas_espana.route('/sevilla')
def versevilla():
    return render_template('españa/sevilla.html')

app/routes/routes_irlanda.py
from flask import Flask, Blueprint, render_template, request, redirect, url_for



rutas_irlanda = Blueprint("ruta_irlanda", __name__)

@rutas_irlanda.route('/')
def index():
    return render_template('index.html')

@rutas_irlanda.route('/verirlanda')
def verirlanda():
    return render_template('irlanda/irlanda.html')

@rutas_irlanda.route('/dublin')
def verdublin():
    return render_template('irlanda/dublin.html')

@rutas_irlanda.route('/galway')
def vergalway():
    return render_template('irlanda/galway.html')

@rutas_irlanda.route('/cork')
def vercork():
    return render_template('irlanda/cork.html')

app/routes/routes_paises.py
from flask import Flask, Blueprint, render_template, request, redirect, url_for
from app import db
from app.data.pais_dao import Pais_dao

rutas_paises = Blueprint("ruta_pais", __name__)

@rutas_paises.route('/')
def index():
    return render_template('index.html')

@rutas_paises.route('/verpaises')
def verpaises():
    pais_dao = Pais_dao()
    paises = pais_dao.select_all(db)

    return render_template('adminpaises.html', paises=paises)

@rutas_paises.route('/addpaises', methods=['POST'])   
def addpaises():
    pais_dao = Pais_dao()

    nombre = request.form['nombre']

    if (nombre == ""):
        return redirect(url_for('ruta_pais.verpaises'))

    pais_dao.insert(db,nombre)
    return redirect(url_for('ruta_pais.verpaises'))    

@rutas_paises.route('/delpaises', methods=['POST'])   
def delpaises():
    id = request.form['id']
    pais_dao = Pais_dao()
    pais_dao.delete(db,id)
   
    return redirect(url_for('ruta_pais.verpaises'))  

@rutas_paises.route('/updatepaises', methods=['POST'])   
def updatepaises():
    pais_dao = Pais_dao()

    nombre = request.form['nombre']

    if (nombre == ""):
        pais_dao.update(db,nombre)
        
    return redirect(url_for('ruta_pais.verpaises'))

app/routes/routes_personajes.py
from flask import Flask, Blueprint, render_template, request, redirect, url_for

from app import db
from app.data.personajes_dao import Personajes_dao
from app.data.pais_dao import Pais_dao

rutas_personajes = Blueprint("ruta_personaje", __name__)

@rutas_personajes.route('/')
def index():
    return render_template('adminpersonajes.html')

@rutas_personajes.route('/verpersonaje', methods=['POST','GET'])
def verpersonaje():
    Personajes = list()
    nombrePais = ""
    pais_dao = Pais_dao()
    paises = pais_dao.select_all(db)

    if (request.method == 'POST'):
        id_pais = request.form['id_pais']
        personaje_dao = Personajes_dao()
        Personajes = personaje_dao.select_all(db,id_pais)
        for pais in paises:
            
            if (id_pais == int(pais.id)):
               
                nombrePais = pais.nombre



    return render_template('adminpersonajes.html',personajes=Personajes,
                           paises=paises,
                           nombrePais=nombrePais)

@rutas_personajes.route('/addpersonaje', methods=['POST'])   
def addpersonaje():
    personaje_dao = Personajes_dao()
    
    nombre = request.form['nombre']
    profesion = request.form['profesion']
    id_pais = request.form['id_pais']

    if (nombre == "" or profesion == "" or id_pais == ""):
        return redirect(url_for('ruta_personaje.verpersonaje'))

    personaje_dao.insert(db,nombre,profesion,id_pais)
  
    return redirect(url_for('ruta_personaje.verpersonaje')) 

@rutas_personajes.route('/delpersonaje', methods=['POST'])   
def delpersonaje():
    id = request.form['id']
    personaje_dao = Personajes_dao()
    personaje_dao.delete(db,id)
    
   
    return redirect(url_for('ruta_personaje.verpersonaje'))  

@rutas_personajes.route('/updatepersonaje', methods=['POST'])   
def updatepersonaje():
    personaje_dao = Personajes_dao()

    id = request.form['id']
    nombre = request.form['nombre']
    profesion = request.form['profesion']

    if (nombre == ""):
        return redirect(url_for('ruta_personaje.verpersonaje'))

    
    personaje_dao.update(db,id,nombre,profesion)
   
    return redirect(url_for('ruta_personaje.verpersonaje'))

app/templates/adminciudades.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="es">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>

<body>

  {% block section %}

  <div>
    <h2>Buscar por pais</h2>
    <form action="/verciudad" method="post">
      <label for="id_paises">Nombre Pais:</label>
      <select name="id_paises">
        {% for pais in paises %}
        <option value="{{pais.id}}">{{pais.nombre}}</option>
        {% endfor %}
      </select>
      <input type="submit" value="Ver" />
    </form>
  </div>

  <br>

  <table style="width: 60%; border: 1px solid black; border-collapse: collapse;">
    <tr>
      <th style="border: 1px solid; padding: 10px;">ID</th>
      <th style="border: 1px solid; padding: 10px;">Ciudades</th>
      <th style="border: 1px solid; padding: 10px;">Contenido</th>
      <th style="border: 1px solid; padding: 10px;">Id Pais</th>
    </tr>
    {% for ciudad in ciudades %}

    <tr>
      <th style="border: 1px solid; padding: 10px;">{{ ciudad.id }}</th>
      <th style="border: 1px solid; padding: 10px;">{{ ciudad.ciudades }}</th>
      <th style="border: 1px solid; padding: 10px;">{{ ciudad.contenido }}</th>
      <th style="border: 1px solid; padding: 10px;">{{ ciudad.id_paises }}</th>
      <th style="border: 1px solid; padding: 10px;">
        <form action="/delciudad" method="post">
          <input type="hidden" name="id" value="{{ciudad.id}}" />
          <input type="submit" value="Borrar" />
        </form>
      </th>
    </tr>
    {% endfor %}

  </table>

  <br>

  <form action="/addciudad" method="post">
    <label for="id">Id</label>
    <input type="text" name="id" value="" />
    <label for="ciudades">Ciudades</label>
    <input type="text" name="ciudades" value="" />
    <label for="contenido">Contenido</label>
    <textarea type="text" name="contenido" value=""></textarea>
    <label for="id_paises">Id pais</label>
    <input type="text" name="id_paises" value="" />
    <input type="submit" value="Añadir" />
  </form>

  <br>

  <form action="/updateciudad" method="post">

    <label for="id">Id</label>
    <select name="id">
      {% for ciudad in ciudades %}
      <option value="{{ciudad.id}}">{{ciudad.id}}</option>
      {% endfor %}
    </select>
    <label for="ciudades">Ciudades</label>
    <input type="text" name="ciudades" value="" />
    <label for="contenido">Contenido</label>
    <textarea type="text" name="contenido" value=""></textarea>

    <input type="submit" value="Actualizar" />
  </form>
  <br>
  {% endblock %}

  {% block footer %}
  <p>ADMIN</p>
  <p>Email: admin@gmail.com</p>
  <p>
    Sígueme en:
    <a href="#" target="_blank">Instagram</a>
    <a href="#" target="_blank">Facebook</a>
  </p>
  {% endblock %}

</body>

</html>

app/templates/adminpaises.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>

<body>

    {% block section %}

    <table style="width: 60%; border: 1px solid black; border-collapse: collapse;">
        <tr>
            <th style="border: 1px solid; padding: 10px;">ID</th>
            <th style="border: 1px solid; padding: 10px;">Nombre</th>
        </tr>

        {% for pais in paises %}
        <tr>
            <th style="border: 1px solid; padding: 10px;">{{ pais.id }}</td>
            <th style="border: 1px solid; padding: 10px;">{{ pais.nombre }}</td>
            <th style="border: 1px solid; padding: 10px;">
                <form action="/delpaises" method="post">
                    <input type="hidden" name="id" value="{{pais.id}}" />
                    <input type="submit" value="Borrar" />
                </form>
            </th>
        </tr>
        {% endfor %}
    </table>

    <br>

    <form action="/addpaises" method="post">
        <label for="id">Id</label>
        <input type="text" name="id" value="" />
        <label for="nombre">Nombre</label>
        <input type="text" name="nombre" value="" />
        <input type="submit" value="Añadir" />
    </form>

    <br>

    <form action="/updatepaises" method="post">
        <label for="paises">Paises:</label>
        <select name="idpaises">
            {% for pais in paises %}
            <option value="{{pais.id}}">{{pais.nombre}}</option>
            {% endfor %}
        </select>
        <label for="nombre">Nombre:</label>
        <input type="text" name="nombre" value="" />
        <input type="submit" value="Actualizar" />
    </form>
    <br>
    {% endblock %}

    {% block footer %}
    <p>ADMIN</p>
    <p>Email: admin@gmail.com</p>
    <p>
        Sígueme en:
        <a href="#" target="_blank">Instagram</a>
        <a href="#" target="_blank">Facebook</a>
    </p>
    {% endblock %}

</body>

</html>

app/templates/adminpersonajes.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>

<body>

    {% block section %}

    <div>
        <h2>Buscar por pais</h2>
        <form action="/verpersonaje" method="post">
            <label for="id_pais">Nombre Pais:</label>
            <select name="id_pais">
                {% for pais in paises %}
                <option value="{{pais.id}}">{{pais.nombre}}</option>
                {% endfor %}
            </select>
            <input type="submit" value="Ver" />
        </form>
    </div>

    <br>

    <table style="width: 60%; border: 1px solid black; border-collapse: collapse;">
        <tr>
            <th style="border: 1px solid; padding: 10px;">ID</th>
            <th style="border: 1px solid; padding: 10px;">Nombre</th>
            <th style="border: 1px solid; padding: 10px;">Profesión</th>
            <th style="border: 1px solid; padding: 10px;">Id_pais</th>
        </tr>

        {% for personaje in personajes %}
        <tr>
            <th style="border: 1px solid; padding: 10px;">{{ personaje.id }}</td>
            <th style="border: 1px solid; padding: 10px;">{{ personaje.nombre }}</td>
            <th style="border: 1px solid; padding: 10px;">{{ personaje.profesion }}</td>
            <th style="border: 1px solid; padding: 10px;">{{ personaje.id_pais }}</td>
            <th style="border: 1px solid; padding: 10px;">
                <form action="/delpersonaje" method="post">
                    <input type="hidden" name="id" value="{{ personaje.id }}" />
                    <input type="submit" value="Borrar" />
                </form>
            </th>
        </tr>
        {% endfor %}
    </table>

    <br>

    <form action="/addpersonaje" method="post">
        <label for="id">Id</label>
        <input type="text" name="id" value="" />
        <label for="nombre">Nombre</label>
        <input type="text" name="id" value="" />
        <label for="profesion">Profesion</label>
        <input type="text" name="id" value="" />
        <label for="id_pais">Id_pais</label>
        <input type="text" name="id" value="" />
        <input type="submit" value="Añadir" />
    </form>

    <br>

    <form action="/updatepersonaje" method="post">
        <label for="personajes">Personajes:</label>
        <select name="idpais">
            {% for personaje in personajes %}
            <option value="{{personaje.id}}">{{personaje.nombre}}</option>
            {% endfor %}
        </select>
        <label for="nombre">Nombre:</label>
        <input type="text" name="nombre" value="" />
        <label for="profesion">Profesion</label>
        <input type="text" name="id" value="" />
        <label for="id_pais">Id_pais</label>
        <input type="text" name="id" value="" />
        <input type="submit" value="Actualizar" />
    </form>
    <br>
    {% endblock %}

    {% block footer %}
    <p>ADMIN</p>
    <p>Email: admin@gmail.com</p>
    <p>
        Sígueme en:
        <a href="#" target="_blank">Instagram</a>
        <a href="#" target="_blank">Facebook</a>
    </p>
    {% endblock %}

</body>

</html>

app/templates/base.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>

<body>
    <nav>
        <div>
            <ul>
                <li><a href="{{ url_for('ruta_irlanda.index') }}">Index</a></li>
                <li><a href="{{ url_for('ruta_pais.verpaises') }}">Admin Paises</a></li>
                <li><a href="{{ url_for('ruta_ciudad.verciudad') }}">Admin Ciudades</a></li>
                <li><a href="{{ url_for('ruta_personaje.verpersonaje') }}">Admin Personajes</a></li>
                {% block croacia %}
                <li><a href="{{ url_for('ruta_croacia.vercroacia') }}">Croacia</a></li>
                {% endblock %}
                {% block españa %}
                <li><a href="{{ url_for('ruta_espana.verespana') }}">España</a></li>
                {% endblock %}
                {% block irlanda %}
                <li><a href="{{ url_for('ruta_irlanda.verirlanda') }}">Irlanda</a></li>
                {% endblock %}
                {% block li %}{% endblock %}
            </ul>
        </div>
    </nav>
    
    <section>
        {% block section %}{% endblock %}
    </section>

    <footer>
        {% block footer %}{% endblock %}
    </footer>
</body>

</html>

app/templates/croacia/croacia.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>

{% block li %}
{% block zagreb %}
<li><a href="{{ url_for('ruta_croacia.verzagreb') }}">Zagreb</a></li>
{% endblock %}
{% block zadar %}
<li><a href="{{ url_for('ruta_croacia.verzadar') }}">Zadar</a></li>
{% endblock %}
{% block split %}
<li><a href="{{ url_for('ruta_croacia.versplit') }}">Split</a></li>
{% endblock %}
{% endblock %}

{% block section %}
{% block croacia %}{% endblock %}
<p class="croacia">Croacia (en croata: Hrvatska), oficialmente República de Croacia (Republika Hrvatskaⓘ), es uno de los
    veintisiete
    Estados soberanos que forman la Unión Europea, ubicado entre Europa Central, Europa meridional y el mar Adriático;
    limita al noreste con Hungría, al este con Serbia, al sureste con Bosnia-Herzegovina y Montenegro, al noroeste con
    Eslovenia y al suroeste con el mar Adriático; donde comparte una frontera marítima con Italia.
</p>
{% endblock %}

{% block footer %}
<p>CROACIA</p>
<p>Email: croacia@gmail.com</p>
<p>
    Sígueme en:
    <a href="#" target="_blank">Instagram</a>
    <a href="#" target="_blank">Facebook</a>
</p>
{% endblock %}

</html>

app/templates/croacia/split.html
{% extends "croacia/croacia.html" %}

{% block section %}
{% block split %}{% endblock %}
<p class="croacia">Split ([splît]ⓘ, en griego antiguo: Ασπάλαθος, Aspálathos; en latín: Spalatum; en italiano: Spalato)
    es una ciudad situada al sur de Croacia, puerto marítimo de la costa dálmata, en el mar Adriático. Cuenta con 221
    456 habitantes, según el censo de 2007.

    Es la principal ciudad de la región de Dalmacia, la capital del condado de Split-Dalmacia y la segunda ciudad más
    populosa del país, después de Zagreb, de la que dista 380 km. Es un importante puerto pesquero y base naval del
    Adriático, así como un centro cultural y turístico importante; la ciudad antigua es una joya arquitectónica,
    declarada Patrimonio de la Humanidad en 1979. En su entorno existen astilleros, fábricas de cemento y de plástico,
    industrias madereras, vitivinícolas y de la alimentación.</p>
{% endblock %}

app/templates/croacia/zadar.html
{% extends "croacia/croacia.html" %}

{% block section %}
{% block zadar %}{% endblock %}
<p class="croacia">Zadara​ ([zât]ⓘ, en italiano: Zara) es una ciudad de la región de Dalmacia en la moderna Croacia.
    Capital del condado homónimo, en el centro-oeste del país y enfrente de las islas Ugljan y Pašman, de las que está
    separada por el estrecho de Zadar.</p>

{% endblock %}

app/templates/croacia/zagreb.html
{% extends "croacia/croacia.html" %}

{% block section %}
{% block zagreb %}{% endblock %}
<p class="croacia">Zagreb (pronunciación en serbocroata: [zǎːɡreb] (escucharⓘ)) es la capital y ciudad más poblada de
    Croacia. Está localizada al noroeste del país, entre el río Sava y la ladera sur del monte Medvednica, a unos 122 m
    s. n. m. Dentro de su término municipal residen más de 850 000 habitantes en 2018, lo que la convierte en la cuarta
    ciudad más grande de Europa Sudoriental y en la segunda por extensión. Si se tienen en cuenta las poblaciones
    limítrofes, la cifra del área pequeña metropolitana asciende a 1 100 000 personas empadronadas.

    La zona sobre la que se asienta Zagreb está habitada desde el Imperio romano. El yacimiento más antiguo que se ha
    localizado es la ciudad romana de Andautonia, situada a 10 km de la actual capital. El término «Zagreb» fue
    registrado por primera vez en 1134 para referirse a la archidiócesis de Zagreb, fundada en 1094,5​ si bien durante
    siglos hubo dos pueblos distintos: Gradec —con bula de oro desde 1242— y Kaptol, donde se hallaba la catedral. Ambas
    localidades se fusionaron en 1851 por orden del ban Josip Jelačić para formar la ciudad actual.5​</p>

{% endblock %}

app/templates/españa/espana.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>

{% block li %}
{% block madrid %}
<li><a href="{{ url_for('ruta_espana.vermadrid') }}">Madrid</a></li>
{% endblock %}
{% block barcelona %}
<li><a href="{{ url_for('ruta_espana.verbarcelona') }}">Barcelona</a></li>
{% endblock %}
{% block sevilla %}
<li><a href="{{ url_for('ruta_espana.versevilla') }}">Sevilla</a></li>
{% endblock %}
{% endblock %}

{% block section %}
{% block españa %}{% endblock %}
<p class="espana">España, formalmente Reino de España,nota 1​ es un país soberano transcontinental, constituido en
    Estado social y
    democrático de derecho y cuya forma de gobierno es la monarquía parlamentaria. Es uno de los veintisiete Estados
    soberanos que forman la Unión Europea. Su territorio, con capital en Madrid,30​ está organizado en diecisiete
    comunidades autónomas, formadas a su vez por cincuenta provincias, y dos ciudades autónomas.
</p>
{% endblock %}

{% block footer %}
<p>ESPAÑA</p>
<p>Email: españa@gmail.com</p>
<p>
    Sígueme en:
    <a href="#" target="_blank">Instagram</a>
    <a href="#" target="_blank">Facebook</a>
</p>
{% endblock %}

</html>

app/templates/index.html
{% extends "base.html" %}
{% block section %}
<p>ESTE ES ES INDEX DE MI PAGINA WEB DE PAISES</p>
<img src="{{ url_for('static', filename='images/images.png') }}" href="{{ url_for('ruta_espana.verespana') }}">
<img src="{{ url_for('static', filename='images/images (1).png') }}" href="{{ url_for('ruta_croacia.vercroacia') }}">
<img src="{{ url_for('static', filename='images/descarga.png') }}" href="{{ url_for('ruta_irlanda.verirlanda') }}">
{% endblock %}
{% block footer %}
<p>INDEX</p>
<p>Email: index@gmail.com</p>
<p>
    Sígueme en:
    <a href="#" target="_blank">Instagram</a>
    <a href="#" target="_blank">Facebook</a>
</p>
{% endblock %}

app/templates/irlanda/galway.html
{% extends "irlanda/irlanda.html" %}

{% block section %}
{% block galway %}{% endblock %}
<p class="irlanda">Galway (en irlandés: Gaillimh) o Galvia es la capital del condado de Galway, en Irlanda. La ciudad se
    encuentra en la costa oeste de la isla, en el rincón noroccidental de la bahía de Galway. El río Corrib atraviesa la
    ciudad. Juvenil y dinámica, es una de las ciudades con más crecimiento económico de la Unión Europea, con una
    población de 79.504 habitantes (según el censo de 2016), aumenta constantemente con la llegada de estudiantes a sus
    dos universidades, la National University of Ireland, Galway y la GMIT.</p>

{% endblock %}

app/templates/irlanda/irlanda.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>

<body>

    {% block li %}
    {% block dublin %}
    <li><a href="{{ url_for('ruta_irlanda.verdublin') }}">Dublin</a></li>
    {% endblock %}
    {% block galway %}
    <li><a href="{{ url_for('ruta_irlanda.vergalway') }}">Galway</a></li>
    {% endblock %}
    {% block cork %}
    <li><a href="{{ url_for('ruta_irlanda.vercork') }}">Cork</a></li>
    {% endblock %}
    {% endblock %}

    {% block section %}
    {% block irlanda %}{% endblock %}

    <p class="irlanda">Irlanda (en irlandés: Éire, pronunciado [ˈeːɾʲə]; en inglés: Ireland, pronunciado /ˈaɪəɹlʲəndʲ/),
        conocida también por su descripción alternativa República de Irlanda (en irlandés: Poblacht na hÉireann; en
        inglés:
        Republic of Ireland)5​ para diferenciarla de Irlanda del Norte, es uno de los veintisiete Estados soberanos que
        forman la Unión Europea. Ocupa la mayor parte de la isla homónima. Su capital y ciudad más poblada es Dublín,
        situada en el este de la isla. El país tiene una única frontera terrestre, con Irlanda del Norte, una de las
        naciones constitutivas del Reino Unido. La isla está rodeada por el océano Atlántico y tiene el mar Céltico al
        sur,
        el canal de San Jorge al sureste y el mar de Irlanda al este. Es una república parlamentaria con un presidente
        electo que ejerce de jefe de Estado. El jefe del gobierno, el Taoiseach, es nombrado por la Cámara Baja del
        Parlamento, la Dáil Éireann.
    </p>
    {% endblock %}

    {% block footer %}

    <p>IRLANDA</p>
    <p>Email: irlanda@gmail.com</p>
    <p>
        Sígueme en:
        <a href="#" target="_blank">Instagram</a>
        <a href="#" target="_blank">Facebook</a>
    </p>

    {% endblock %}

</body>

</html>